export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_RESET = "AUTH_RESET";
export const GET_AUTH = "GET_AUTH";

export const GET_CONTACTS_DATA = "GET_CONTACTS_DATA";
export const SET_CONTACTS_DATA = "SET_CONTACTS_DATA";
export const TOGGEL_OPEN_MEDIA = "TOGGEL_OPEN_MEDIA";

export const DISPLAY = "DISPLAY";
export const NOT_DISPLAY = "NOT_DISPLAY";

export const WHATSAPP_START = "WHATSAPP_START";
export const WHATSAPP_QR_SUCCESS = "WHATSAPP_QR_SUCCESS";
export const WHATSAPP_FAILURE = "WHATSAPP_FAILURE";
export const CHANGE_QR_CODE = "CHANGE_QR_CODE";
export const STATUS_WHATSAAP_CONECTION = "STATUS_WHATSAAP_CONECTION";
export const WHATSAAP_DISCONNECTED = "WHATSAAP_DISCONNECTED";
export const CHANGE_KEY_QR_DATA = "CHANGE_KEY_QR_DATA";
export const UPDATE_MSG_IN_CHAT = "UPDATE_MSG_IN_CHAT";
export const LOAD_MESSAGES_IN_SELECT_CHAT = "LOAD_MESSAGES_IN_SELECT_CHAT";
export const LOAD_PROFIL_PIC = "LOAD_PROFIL_PIC";
export const SERVER_DOWNLOAD_MEDIA = "SERVER_DOWNLOAD_MEDIA";
